import fs from 'node:fs';
import path from 'node:path';

import { getSourcePath } from '../utils/getSourcePath';
import { writeFile } from '../utils/writeFile';

const SVG_SOURCE_DIR = 'packages/icons/src/svgs';
const OUTPUT_PATH = 'apps/test-expo/src/__generated__/iconSvgMap.ts';

const HEADER = `/**
 * DO NOT MODIFY
 * This file is generated by libs/codegen/src/icons/generateIconSvgMap.ts
 *
 * Why this exists:
 * - Provides a static map of icon names to their SVG content for rendering Icons directly with react-native-svg components
 *
 * What this provides:
 * - A static map of iconName-12|16|24|32-active|inactive → { content: "svg-string" }
 *
 * Usage:
 * - Access SVG string content via: svgMap['icon-name-12-active'].content
 */`;

export function generateIconSvgMap(): void {
  console.log('Generating React Native SVG map...');

  const svgDir = getSourcePath(SVG_SOURCE_DIR);
  const svgFiles = fs
    .readdirSync(svgDir)
    .filter((file) => file.endsWith('.svg'))
    .sort((a, b) => a.localeCompare(b));

  if (svgFiles.length === 0) {
    console.log('No SVG files found, skipping SVG map generation');
    return;
  }

  const mapEntries = svgFiles.map((file) => {
    const base = file.replace(/\.svg$/, '');
    const svgContent = fs.readFileSync(path.join(svgDir, file), 'utf8');
    const escaped = svgContent
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
    return `  '${base}': { content: "${escaped}" },`;
  });

  const content = `${HEADER}

export const svgMap: Record<string, SvgMapEntry> = {
${mapEntries.join('\n')}
} as const;

export type SvgMapEntry = { content: string };
export type SvgMap = Record<string, SvgMapEntry>;
export type SvgKey = keyof typeof svgMap;

export default svgMap;
`;

  void writeFile({
    data: content,
    dest: OUTPUT_PATH,
    config: { disablePrettier: true },
  }).then(() => {
    console.log(`Generated React Native SVG map with ${svgFiles.length} entries -> ${OUTPUT_PATH}`);
  });
}

generateIconSvgMap();
